#!/bin/python3

import sys


t = int(input().strip())
for a0 in range(t):
    n = int(input().strip())   
    s = 0
    res3=0

    if n <= 10:
        i = (n-1)//3
        f = (n-1)//5

        res1 = (i/2)*(2*3+3*(i-1))     
        res2 = (f/2)*(2*5+0*(f-1))

        print(int(res1 + res2 ))

    else:    
        i = (n-1)//3
        f = (n-1)//5
        x = (n-1)//15

        res1 = (2*3+3*(i-1))
        res2 = (2*5+5*(f-1))
        res3 = (2*15+15*(x-1))

        print(int(res1*(i>>1) + res2*(f>>1) - res3*(x>>1))) // no funciona la division
